firebase/FirebaseUI-Flutter

packages/firebase_ui_localizations/lib/l10n/firebase_ui_ru.arb
packages/firebase_ui_localizations/lib/src/lang/ru.dart

Elimination of duplicates in the Russian dictionary: removal of repetitive English words has been performed, as they are unnecessary for functionality.
Due to these duplicates, elements of the user interface appear overloaded, often resulting in overflow. …

fix: update ru translations to remove English duplicates

---

packages/firebase_ui_auth/example/lib/main.dart
packages/firebase_ui_auth/example/pubspec.yaml

chore(ui_auth): refactor Firebase UI Auth example to Dart 3

---

CHANGELOG.md
packages/firebase_ui_auth/CHANGELOG.md
packages/firebase_ui_auth/example/pubspec.yaml
packages/firebase_ui_auth/pubspec.yaml
packages/firebase_ui_database/CHANGELOG.md
packages/firebase_ui_database/example/pubspec.yaml
packages/firebase_ui_database/pubspec.yaml
packages/firebase_ui_firestore/CHANGELOG.md
packages/firebase_ui_firestore/example/pubspec.yaml
packages/firebase_ui_firestore/pubspec.yaml
packages/firebase_ui_localizations/CHANGELOG.md
packages/firebase_ui_localizations/example/pubspec.yaml
packages/firebase_ui_localizations/pubspec.yaml
packages/firebase_ui_oauth/CHANGELOG.md
packages/firebase_ui_oauth/example/pubspec.yaml
packages/firebase_ui_oauth/pubspec.yaml
packages/firebase_ui_oauth_apple/CHANGELOG.md
packages/firebase_ui_oauth_apple/pubspec.yaml
packages/firebase_ui_oauth_facebook/CHANGELOG.md
packages/firebase_ui_oauth_facebook/pubspec.yaml
packages/firebase_ui_oauth_google/CHANGELOG.md
packages/firebase_ui_oauth_google/pubspec.yaml
packages/firebase_ui_oauth_twitter/CHANGELOG.md
packages/firebase_ui_oauth_twitter/pubspec.yaml

chore(release): prepare for release

---

packages/firebase_ui_storage/example/lib/main.dart
packages/firebase_ui_storage/example/lib/src/apps.dart
packages/firebase_ui_storage/example/lib/storybook.dart
packages/firebase_ui_storage/example/macos/Runner.xcodeproj/project.pbxproj
packages/firebase_ui_storage/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme

chore(ui_storage): update Firebase UI Storage example

---

packages/firebase_ui_auth/example/android/build.gradle
packages/firebase_ui_auth/example/ios/Podfile
packages/firebase_ui_auth/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_ui_auth/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/firebase_ui_auth/example/ios/Runner/Info.plist
packages/firebase_ui_auth/example/macos/Runner.xcodeproj/project.pbxproj
packages/firebase_ui_auth/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme

chore(ui_auth): update example

---

packages/firebase_ui_auth/example/pubspec.yaml
packages/firebase_ui_auth/pubspec.yaml
packages/firebase_ui_database/pubspec.yaml
packages/firebase_ui_firestore/pubspec.yaml
packages/firebase_ui_oauth/example/pubspec.yaml
packages/firebase_ui_oauth/pubspec.yaml
packages/firebase_ui_oauth_apple/pubspec.yaml
packages/firebase_ui_oauth_facebook/pubspec.yaml
packages/firebase_ui_oauth_google/pubspec.yaml
packages/firebase_ui_oauth_twitter/pubspec.yaml
packages/firebase_ui_storage/pubspec.yaml

chore: upgrade dependencies

---

packages/firebase_ui_auth/doc/README.md
packages/firebase_ui_auth/example/windows/flutter/generated_plugin_registrant.cc
packages/firebase_ui_auth/example/windows/flutter/generated_plugins.cmake
packages/firebase_ui_auth/lib/firebase_ui_auth.dart
packages/firebase_ui_auth/lib/src/screens/sign_in_screen.dart
packages/firebase_ui_auth/test/screens/sign_in_screen_test.dart
packages/firebase_ui_auth/test/test_utils.dart
packages/firebase_ui_auth/test/views/login_view_test.dart
packages/firebase_ui_localizations/example/windows/flutter/generated_plugin_registrant.cc
packages/firebase_ui_localizations/example/windows/flutter/generated_plugins.cmake
packages/firebase_ui_oauth/example/windows/flutter/generated_plugin_registrant.cc
packages/firebase_ui_oauth/example/windows/flutter/generated_plugins.cmake

fix(ui_auth): add showPasswordVisibilityToggle to the SignInScreen

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml

This PR removes the label and assignee event from the issue template so that the issue falls into the primary triage queue.  …

chore: remove label and assignee from issue template

---

packages/firebase_ui_auth/example/windows/flutter/generated_plugin_registrant.cc
packages/firebase_ui_auth/example/windows/flutter/generated_plugins.cmake
packages/firebase_ui_localizations/example/windows/flutter/generated_plugin_registrant.cc
packages/firebase_ui_localizations/example/windows/flutter/generated_plugins.cmake
packages/firebase_ui_localizations/lib/l10n/firebase_ui_it.arb
packages/firebase_ui_localizations/lib/src/lang/it.dart
packages/firebase_ui_oauth/example/windows/flutter/generated_plugin_registrant.cc
packages/firebase_ui_oauth/example/windows/flutter/generated_plugins.cmake

update Italian translations (specifically for EmailVerificationScreen) 
nothing

fix(ui_localizations): update italian translations

---

packages/firebase_ui_auth/example/pubspec.yaml
packages/firebase_ui_auth/pubspec.yaml
packages/firebase_ui_database/example/pubspec.yaml
packages/firebase_ui_database/pubspec.yaml
packages/firebase_ui_firestore/example/pubspec.yaml
packages/firebase_ui_firestore/pubspec.yaml
packages/firebase_ui_localizations/example/pubspec.yaml
packages/firebase_ui_oauth/example/pubspec.yaml
packages/firebase_ui_oauth/pubspec.yaml
packages/firebase_ui_oauth_apple/pubspec.yaml
packages/firebase_ui_oauth_facebook/pubspec.yaml
packages/firebase_ui_oauth_google/pubspec.yaml
packages/firebase_ui_oauth_twitter/pubspec.yaml
packages/firebase_ui_storage/example/pubspec.yaml
tests/pubspec.yaml

chore: bump dependencies

---

packages/firebase_ui_oauth_apple/lib/src/provider.dart

fix(ui_oauth_apple): fix AuthAction.link for Apple Sign In

---

packages/firebase_ui_localizations/lib/l10n/firebase_ui_ro.arb
packages/firebase_ui_localizations/lib/src/all_languages.dart
packages/firebase_ui_localizations/lib/src/lang/ro.dart

Add localization for romanian language.

feat(ui_localizations): Add Romanian localization

---

packages/firebase_ui_auth/lib/src/screens/phone_input_screen.dart
packages/firebase_ui_auth/lib/src/views/phone_input_view.dart
tests/integration_test/firebase_ui_auth/phone_verification_test.dart

fix: phone input screen footer position

---

packages/firebase_ui_auth/lib/src/auth_flow.dart
packages/firebase_ui_auth/lib/src/flows/email_flow.dart
packages/firebase_ui_auth/lib/src/flows/oauth_flow.dart
packages/firebase_ui_auth/lib/src/flows/phone_auth_flow.dart
packages/firebase_ui_auth/lib/src/flows/universal_email_sign_in_flow.dart
packages/firebase_ui_auth/lib/src/screens/sms_code_input_screen.dart
packages/firebase_ui_auth/lib/src/widgets/internal/universal_text_form_field.dart
packages/firebase_ui_auth/pubspec.yaml
packages/firebase_ui_oauth/lib/src/oauth_provider_button_base.dart
tests/integration_test/firebase_ui_auth/phone_verification_test.dart
tests/integration_test/utils.dart
tests/ios/Podfile
tests/macos/Podfile

chore: fix CI

---

.github/workflows/e2e.yml

chore: use node 18 for firebase emulator

---

packages/firebase_ui_localizations/lib/l10n/firebase_ui_ro.arb

Update translation strings in Romanian for confirm account deletion.

fix: Update translation strings in RO for confirm account deletion

---

packages/firebase_ui_firestore/lib/src/table_builder.dart

fix(ui_firestore): null-assert count for aggregate query

---

database.rules.json
firebase.json
melos.yaml
tests/integration_test/firebase_ui_database/database_list_view_test.dart
tests/integration_test/firebase_ui_database/firebase_ui_database.dart
tests/integration_test/firebase_ui_test.dart
tests/integration_test/utils.dart
tests/ios/Podfile
tests/linux/flutter/generated_plugin_registrant.cc
tests/linux/flutter/generated_plugins.cmake
tests/pubspec.yaml
tests/windows/flutter/generated_plugin_registrant.cc
tests/windows/flutter/generated_plugins.cmake

test(firebase_ui_database): update e2e tests and integrate into CI

---

packages/firebase_ui_localizations/lib/src/lang/ro.dart

Added missing generated translation file from src/lang folder for Romanian language.

fix(ui_localizations): Update missing generated translations for Romanian language

---

CHANGELOG.md
packages/firebase_ui_auth/CHANGELOG.md
packages/firebase_ui_auth/example/pubspec.yaml
packages/firebase_ui_auth/pubspec.yaml
packages/firebase_ui_database/CHANGELOG.md
packages/firebase_ui_database/example/pubspec.yaml
packages/firebase_ui_database/pubspec.yaml
packages/firebase_ui_firestore/CHANGELOG.md
packages/firebase_ui_firestore/example/pubspec.yaml
packages/firebase_ui_firestore/pubspec.yaml
packages/firebase_ui_localizations/CHANGELOG.md
packages/firebase_ui_localizations/example/pubspec.yaml
packages/firebase_ui_localizations/pubspec.yaml
packages/firebase_ui_oauth/CHANGELOG.md
packages/firebase_ui_oauth/example/pubspec.yaml
packages/firebase_ui_oauth/pubspec.yaml
packages/firebase_ui_oauth_apple/CHANGELOG.md
packages/firebase_ui_oauth_apple/pubspec.yaml
packages/firebase_ui_oauth_facebook/CHANGELOG.md
packages/firebase_ui_oauth_facebook/pubspec.yaml
packages/firebase_ui_oauth_google/CHANGELOG.md
packages/firebase_ui_oauth_google/pubspec.yaml
packages/firebase_ui_oauth_twitter/CHANGELOG.md
packages/firebase_ui_oauth_twitter/pubspec.yaml
packages/firebase_ui_storage/CHANGELOG.md
packages/firebase_ui_storage/example/pubspec.yaml
packages/firebase_ui_storage/pubspec.yaml
tests/pubspec.yaml

- firebase_ui_auth@1.13.0
- firebase_ui_localizations@1.10.2
- firebase_ui_oauth@1.5.0
- firebase_ui_oauth_google@1.3.0
- firebase_ui_oauth_facebook@1.2.18
- firebase_ui_oauth_twitter@1.2.18
- firebase_ui_oauth_apple@1.2.18
- firebase_ui_firestore@1.6.2
- firebase_ui_database@1.4.2
- firebase_ui_storage@2.0.3
Flutter-UI release.
Does your PR …

chore(release): publish packages

---

.github/workflows/e2e.yml

ci: update android CI workflow to use `ubuntu-latest` runner

---

packages/firebase_ui_oauth/lib/src/platform_oauth_sign_in_web.dart

see title.
fixes https://github.com/firebase/FirebaseUI-Flutter/issues/286

fix(auth): `desktopSignIn()` method required in web mixin

---

tests/ios/Podfile
tests/macos/Podfile

ci(apple): use latest firebase-ios-sdk framework

---

packages/firebase_ui_auth/example/android/app/build.gradle
packages/firebase_ui_auth/example/android/app/google-services.json
packages/firebase_ui_auth/example/android/build.gradle
packages/firebase_ui_auth/example/android/gradle.properties
packages/firebase_ui_auth/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_ui_auth/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/firebase_ui_auth/example/ios/Runner/GoogleService-Info.plist
packages/firebase_ui_auth/example/ios/Runner/Info.plist
packages/firebase_ui_auth/example/lib/config.dart
packages/firebase_ui_auth/example/pubspec.yaml
packages/firebase_ui_auth/pubspec.yaml

chore(auth): update auth example app so Google authentication works

---

packages/firebase_ui_auth/README.md

Added super key to example widget to make it more easy to copy paste and use

docs: Added superkey to example widget

---

docs/firebase-ui-auth/providers/oauth.md

Fix typo s/TargetPlatfrom/TargetPlatform
Fix typo s/TargetPlatfrom/TargetPlatform in oauth.md instructions …

docs: Updated `oauth.md` - fixed typo

---

functions/package-lock.json
functions/package.json

ci: revert firebase-admin version bump for cloud functions

---

.github/workflows/code_health.yml
packages/firebase_ui_firestore/test/table_builder_test.dart

ci: update Mock test to latest and switch Runner for format check

---

tests/ios/Podfile
tests/macos/Podfile

ci(apple): update firestore-ios-frameworks

---

packages/firebase_ui_auth/example/lib/main.dart
packages/firebase_ui_shared/lib/src/universal_button.dart

chore: replace deprecated `MaterialStateProperty` + `MaterialStateColor` with `WidgetStateProperty` + `WidgetStateColor`

---

packages/firebase_ui_auth/example/pubspec.yaml
packages/firebase_ui_auth/lib/src/email_verification.dart
packages/firebase_ui_auth/lib/src/providers/email_link_auth_provider.dart
packages/firebase_ui_auth/pubspec.yaml
packages/firebase_ui_auth/test/test_utils.dart
packages/firebase_ui_database/example/pubspec.yaml
packages/firebase_ui_database/pubspec.yaml
packages/firebase_ui_firestore/example/pubspec.yaml
packages/firebase_ui_firestore/pubspec.yaml
packages/firebase_ui_localizations/example/pubspec.yaml
packages/firebase_ui_oauth/example/pubspec.yaml
packages/firebase_ui_oauth/pubspec.yaml
packages/firebase_ui_oauth_apple/pubspec.yaml
packages/firebase_ui_oauth_facebook/pubspec.yaml
packages/firebase_ui_oauth_google/pubspec.yaml
packages/firebase_ui_oauth_twitter/pubspec.yaml
packages/firebase_ui_storage/example/pubspec.yaml
packages/firebase_ui_storage/pubspec.yaml
tests/android/app/build.gradle
tests/ios/Podfile
tests/macos/Podfile
tests/pubspec.yaml

fixes https://github.com/firebase/FirebaseUI-Flutter/issues/355 …

chore: bump all FlutterFire dependencies to latest

---

.github/workflows/e2e.yml
packages/firebase_ui_auth/example/windows/flutter/generated_plugins.cmake
tests/integration_test/firebase_ui_auth/actions_test.dart
tests/integration_test/firebase_ui_auth/email_form_test.dart
tests/integration_test/firebase_ui_auth/phone_verification_test.dart
tests/integration_test/firebase_ui_database/database_list_view_test.dart
tests/integration_test/utils.dart
tests/ios/Runner.xcodeproj/project.pbxproj
tests/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
tests/ios/Runner/AppDelegate.swift

test: skip test failing in CI

---

packages/firebase_ui_firestore/example/android/build.gradle

chore(firestore): fix example app on android

---

.github/workflows/issue-labels.yml
CONTRIBUTING.md
melos.yaml

ci: update contributing guide & automatically label issues that need attention

---

docs/firebase-ui-auth/providers/email-verification.md

Addresses questions in https://github.com/firebase/FirebaseUI-Flutter/issues/221
closes https://github.com/firebase/FirebaseUI-Flutter/issues/221#issuecomment-2347331312
[Contributor …

docs(auth): inform user what to do when using simulator for email verification

---

packages/firebase_ui_auth/example/pubspec.yaml
packages/firebase_ui_auth/pubspec.yaml
packages/firebase_ui_database/example/pubspec.yaml
packages/firebase_ui_database/pubspec.yaml
packages/firebase_ui_firestore/example/pubspec.yaml
packages/firebase_ui_firestore/pubspec.yaml
packages/firebase_ui_localizations/example/pubspec.yaml
packages/firebase_ui_oauth/example/pubspec.yaml
packages/firebase_ui_oauth/pubspec.yaml
packages/firebase_ui_oauth_apple/pubspec.yaml
packages/firebase_ui_oauth_facebook/pubspec.yaml
packages/firebase_ui_oauth_google/pubspec.yaml
packages/firebase_ui_oauth_twitter/pubspec.yaml
packages/firebase_ui_storage/example/pubspec.yaml
packages/firebase_ui_storage/pubspec.yaml
tests/pubspec.yaml

chore: bump to the latest FlutterFire dependencies

---

.github/workflows/issue-labels.yml

chore: add "Needs attention" label to new issues

---

packages/firebase_ui_auth/example/pubspec.yaml
packages/firebase_ui_auth/pubspec.yaml
packages/firebase_ui_database/example/pubspec.yaml
packages/firebase_ui_database/pubspec.yaml
packages/firebase_ui_firestore/example/pubspec.yaml
packages/firebase_ui_firestore/pubspec.yaml
packages/firebase_ui_localizations/example/pubspec.yaml
packages/firebase_ui_oauth/example/pubspec.yaml
packages/firebase_ui_oauth/pubspec.yaml
packages/firebase_ui_oauth_apple/pubspec.yaml
packages/firebase_ui_oauth_facebook/pubspec.yaml
packages/firebase_ui_oauth_google/pubspec.yaml
packages/firebase_ui_oauth_twitter/pubspec.yaml
packages/firebase_ui_storage/example/pubspec.yaml
packages/firebase_ui_storage/pubspec.yaml
tests/ios/Podfile
tests/macos/Podfile
tests/pubspec.yaml

feat: bump FlutterFire dependencies 2024-09-30

---

.github/workflows/issue-labels.yml

- ensure `Needs Attention` is applied to new issues.
- ensure `blocked: customer response` label is removed when user responds. …

chore: fix automatic labelling workflow

---

packages/firebase_ui_auth/lib/src/widgets/editable_user_display_name.dart

See console log of changes:
fixes https://github.com/firebase/FirebaseUI-Flutter/issues/428

fix(auth): ensure previous display name is provided to callback

---

.github/workflows/issue-labels.yml
.github/workflows/stale.yml

chore: workflow for checking stale issues and PRs

---

packages/firebase_ui_auth/example/pubspec.yaml
packages/firebase_ui_auth/pubspec.yaml
packages/firebase_ui_database/example/pubspec.yaml
packages/firebase_ui_database/pubspec.yaml
packages/firebase_ui_firestore/example/pubspec.yaml
packages/firebase_ui_firestore/pubspec.yaml
packages/firebase_ui_localizations/example/pubspec.yaml
packages/firebase_ui_oauth/example/pubspec.yaml
packages/firebase_ui_oauth/pubspec.yaml
packages/firebase_ui_oauth_apple/pubspec.yaml
packages/firebase_ui_oauth_facebook/pubspec.yaml
packages/firebase_ui_oauth_google/pubspec.yaml
packages/firebase_ui_oauth_twitter/pubspec.yaml
packages/firebase_ui_storage/example/pubspec.yaml
packages/firebase_ui_storage/pubspec.yaml
tests/ios/Podfile
tests/macos/Podfile
tests/pubspec.yaml

chore: bump FlutterFire dependencies to latest

---

packages/firebase_ui_auth/example/pubspec.yaml
packages/firebase_ui_auth/pubspec.yaml
packages/firebase_ui_auth/test/widgets/error_text_test.dart
packages/firebase_ui_database/example/pubspec.yaml
packages/firebase_ui_database/pubspec.yaml
packages/firebase_ui_firestore/example/pubspec.yaml
packages/firebase_ui_firestore/pubspec.yaml
packages/firebase_ui_localizations/example/lib/main.dart
packages/firebase_ui_localizations/example/pubspec.yaml
packages/firebase_ui_oauth/example/pubspec.yaml
packages/firebase_ui_oauth/pubspec.yaml
packages/firebase_ui_oauth_apple/pubspec.yaml
packages/firebase_ui_oauth_facebook/pubspec.yaml
packages/firebase_ui_oauth_google/pubspec.yaml
packages/firebase_ui_oauth_twitter/pubspec.yaml
packages/firebase_ui_storage/example/pubspec.yaml
packages/firebase_ui_storage/pubspec.yaml
tests/ios/Podfile
tests/macos/Podfile
tests/pubspec.yaml

fix: bump FF dependencies to latest
