firebase/FirebaseUI-Flutter

- melos.yaml
- packages/firebase_ui_auth/.gitignore
- packages/firebase_ui_auth/example/pubspec.yaml
- packages/firebase_ui_auth/pubspec.yaml
- packages/firebase_ui_database/.gitignore
- packages/firebase_ui_firestore/.gitignore
- packages/firebase_ui_localizations/example/pubspec_overrides.yaml
- packages/firebase_ui_oauth/.gitignore
- packages/firebase_ui_oauth_apple/.gitignore
- packages/firebase_ui_oauth_facebook/.gitignore
- packages/firebase_ui_oauth_facebook/pubspec.yaml
- packages/firebase_ui_oauth_google/.gitignore
- packages/firebase_ui_oauth_twitter/.gitignore
- packages/firebase_ui_storage/pubspec.yaml
> chore: update dependencies

- packages/firebase_ui_auth/lib/src/views/email_link_sign_in_view.dart
- packages/firebase_ui_auth/test/views/email_link_sign_in_view_test.dart
This PR adds a "Go back" button to EmailLinkSignInView. Other views and screens in firebase_ui_auth have
a similar button already, but EmailLinkSignInView does not, so users can get stuck if they got there by mistake,
mistyped their email address, etc. This button code was copied from SMSCodeInputScreen, so it should be
consistent with other auth flows in the package.
Fixes #81
[Contributor …
> feat(firebase_ui_auth): Add "Go Back" button to EmailLinkSignInView

- packages/firebase_ui_auth/lib/src/views/login_view.dart
- packages/firebase_ui_auth/test/src/views/login_view_test.dart
This change is needed to rebuild the footer when the action changes (for example when the user click on the header auth action switch)
None …
> fix(ui_auth): Pass correct AuthAction to the footerBuilder

- packages/firebase_ui_storage/README.md
- packages/firebase_ui_storage/doc/getting-started.md
- packages/firebase_ui_storage/doc/grid-view.md
- packages/firebase_ui_storage/doc/list-view.md
- packages/firebase_ui_storage/doc/paginated-loading-controller.md
- packages/firebase_ui_storage/doc/storage-image.md
- packages/firebase_ui_storage/doc/task-progress-indicator.md
- packages/firebase_ui_storage/doc/upload-button.md
- packages/firebase_ui_storage/lib/firebase_ui_storage.dart
- packages/firebase_ui_storage/lib/src/widgets/grid_view.dart
- packages/firebase_ui_storage/lib/src/widgets/progress_indicator.dart
> docs(ui_storage): add Firebase UI Storage docs

- packages/firebase_ui_auth/lib/src/widgets/email_form.dart
- packages/firebase_ui_auth/test/widgets/email_form_test.dart
> fix(ui_auth): allow to pass EmailFormStyle via property

- packages/firebase_ui_auth/lib/src/screens/internal/login_screen.dart
- packages/firebase_ui_auth/lib/src/views/different_method_sign_in_view.dart
- packages/firebase_ui_auth/lib/src/views/login_view.dart
- packages/firebase_ui_auth/lib/src/views/reauthenticate_view.dart
- packages/firebase_ui_auth/lib/src/widgets/email_form.dart
- packages/firebase_ui_auth/lib/src/widgets/email_sign_up_dialog.dart
- packages/firebase_ui_auth/lib/src/widgets/internal/universal_icon_button.dart
- packages/firebase_ui_auth/lib/src/widgets/internal/universal_text_form_field.dart
- packages/firebase_ui_auth/lib/src/widgets/password_input.dart
- packages/firebase_ui_auth/test/widgets/email_form_test.dart
> feat(ui_auth): allow to toggle password visibility

- packages/firebase_ui_auth/lib/src/widgets/error_text.dart
- packages/firebase_ui_auth/test/widgets/error_text_test.dart
> feat(ui_auth): add a way to customize ErrorText message

- packages/firebase_ui_localizations/lib/src/all_languages.dart
- packages/firebase_ui_localizations/lib/src/l10n.dart
- packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart
I found that the `firebase_ui_localizations` package includes a translation for Taiwan (`ZhTWLocalizations`), but has not been used appropriately. So I follow the same approach of how the `flutter_localizations` package gets the appropriate translation and how to fallback when the `scriptCode` or `countryCode` is not defined.
Closes #33  …
> fix(ui_localizations): loading Traditional Chinese

- packages/firebase_ui_auth/README.md
The docs are use dashes in `firebase-ui-auth`, rather than underscores that the code does (`firebase_ui_auth`).
The docs links on https://pub.dev/packages/firebase_ui_auth don't work, because they link to the wrong URLs. This PR fixes the URLs. …
> docs: Update README.md for AuthUI to fix links to docs pages

- packages/firebase_ui_auth/lib/src/navigation/authentication.dart
- packages/firebase_ui_auth/lib/src/widgets/reauthenticate_dialog.dart
- packages/firebase_ui_auth/test/test_utils.dart
- packages/firebase_ui_auth/test/widgets/dialogs_test.dart
- packages/firebase_ui_oauth/lib/src/oauth_provider_button_base.dart
- tests/integration_test/firebase_ui_auth/layout_test.dart
> fix(ui_auth): use capitalized cancel label on dialogs

- packages/firebase_ui_auth/lib/src/auth_flow.dart
- packages/firebase_ui_auth/lib/src/flows/universal_email_sign_in_flow.dart
- packages/firebase_ui_auth/lib/src/providers/auth_provider.dart
- packages/firebase_ui_auth/lib/src/providers/universal_email_sign_in_provider.dart
- packages/firebase_ui_auth/lib/src/screens/universal_email_sign_in_screen.dart
- packages/firebase_ui_auth/lib/src/views/find_providers_for_email_view.dart
- packages/firebase_ui_auth/lib/src/widgets/auth_flow_builder.dart
- packages/firebase_ui_auth/test/flows/universal_email_sign_in_flow_test.dart
- tests/integration_test/firebase_ui_auth/universal_email_sign_in_screen_test.dart
Email enumeration protection is on by default for new projects. This breaks UniversalEmailSignInScreen and other Firebase UI Auth APIs that use fetchSignInMethodsForEmail under the hood.
Read more details here https://cloud.google.com/identity-platform/docs/admin/email-enumeration-protection
Closes #148 …
> fix(ui_auth): deprecate functionality that uses fetchSignInMethodsForEmail

- packages/firebase_ui_auth/lib/src/widgets/error_text.dart
> feat(ui_auth): add a way to customize PlatformException text

- packages/firebase_ui_auth/lib/src/actions.dart
- packages/firebase_ui_auth/lib/src/widgets/delete_account_button.dart
- packages/firebase_ui_auth/lib/src/widgets/editable_user_display_name.dart
- AccountDeletedAction
- DisplayNameChangedAction
Closes #136
> feat(ui_auth): add more account actions

- packages/firebase_ui_auth/lib/src/screens/email_link_sign_in_screen.dart
- packages/firebase_ui_auth/lib/src/screens/email_verification_screen.dart
- packages/firebase_ui_auth/lib/src/screens/forgot_password_screen.dart
- packages/firebase_ui_auth/lib/src/screens/internal/login_screen.dart
- packages/firebase_ui_auth/lib/src/screens/phone_input_screen.dart
- packages/firebase_ui_auth/lib/src/screens/register_screen.dart
- packages/firebase_ui_auth/lib/src/screens/sign_in_screen.dart
> fix(ui_auth): make maxWidth configurable on all screens

- packages/firebase_ui_auth/lib/src/actions.dart
- tests/integration_test/firebase_ui_auth/actions_test.dart
- tests/integration_test/firebase_ui_auth/firebase_ui_auth_e2e.dart
- tests/integration_test/firebase_ui_test.dart
- tests/integration_test/utils.dart
> feat(ui_auth): add a way to get an AuthController for AuthState

- packages/firebase_ui_auth/lib/firebase_ui_auth.dart
- packages/firebase_ui_auth/lib/src/auth_flow.dart
- packages/firebase_ui_auth/lib/src/auth_state.dart
- packages/firebase_ui_auth/lib/src/navigation/authentication.dart
- packages/firebase_ui_auth/lib/src/providers/auth_provider.dart
- packages/firebase_ui_auth/lib/src/screens/sign_in_screen.dart
- packages/firebase_ui_auth/lib/src/views/different_method_sign_in_view.dart
- packages/firebase_ui_auth/lib/src/widgets/different_method_sign_in_dialog.dart
- packages/firebase_ui_auth/test/widgets/dialogs_test.dart
> fix(ui_auth): deprecate email enumeration protection affected APIs

- packages/firebase_ui_auth/lib/src/navigation/authentication.dart
- packages/firebase_ui_auth/lib/src/views/reauthenticate_view.dart
- packages/firebase_ui_auth/lib/src/widgets/reauthenticate_dialog.dart
- tests/integration_test/firebase_ui_auth/phone_verification_test.dart
- tests/integration_test/utils.dart
> fix(ui_auth): correctly handle phone auth in showReauthenticateDialog

- packages/firebase_ui_firestore/lib/src/table_builder.dart
> fix(ui_firestore): A value of type 'int?' can't be returned from a function with return type 'int' because 'int?

- packages/firebase_ui_firestore/lib/src/table_builder.dart
Reverts firebase/FirebaseUI-Flutter#241
> chore: Revert "fix(ui_firestore): A value of type 'int?' can't be returned from a function with return type 'int' because 'int?"

- packages/firebase_ui_auth/lib/src/screens/register_screen.dart
- packages/firebase_ui_auth/test/screens/register_screen_test.dart
Currently, `showPasswordVisibilityToggle` is available on SignInScreen, but not on RegisterScreen. 
#114
> feat(firebase_ui_auth): add `showPasswordVisibilityToggle` to `RegisterScreen`

- packages/firebase_ui_localizations/lib/l10n/firebase_ui_ja.arb
- packages/firebase_ui_localizations/lib/src/lang/ja.dart
* In the Japanese translation file, "Login" and "Sign in" are mixed, so I unified them with "Sign in" to match the English version.
* There may be some debate as to whether to use "Login" or "Sign In" for this, but I decided to go with the English version.
* Removed unnatural spaces in Japanese.
> * 日本語翻訳ファイルにおいて、「ログイン」と「サインイン」が混在しているので、英語版に合わせて「サインイン」に統一しました。
>   * 「ログイン」と「サインイン」のどちらを使うべきかには議論があるかもしれませんが、英語版に合わせることにしました。
> * 日本語の不自然な空白を削除しました。
none
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-r …
> fix(ui_localizations): In the Japanese file, change "login" to "sign and improve translations

- packages/firebase_ui_auth/lib/src/views/email_link_sign_in_view.dart
Fixed an issue where the email address input form was briefly redisplayed upon completing sign-in with EmailLinkAuth.
For now, I've prevented it from going back to the form display, but showing a loading indicator might also be a good idea.
none …
> fix(ui_auth): Fixed a momentary form display after signing in with EmailLinkAuth.

- packages/firebase_ui_auth/lib/src/views/forgot_password_view.dart
- packages/firebase_ui_auth/test/views/forgot_password_view_test.dart
Even when ForgotPasswordView has isLoading=true,  `sendPasswordResetEmail` is executed the number of times the button is pressed.
I don't see any advantage for users to receive more than one email.
In this PR, if isLoading is true, the mail is not sent. …
> fix(firebase_ui_auth): `sendPasswordResetEmail` should not be executed when `isLoading=true`

- packages/firebase_ui_auth/lib/src/widgets/email_form.dart
If we set the `email` property like below:
```dart
SignInScreen(
email: 'some@email.com',
actions: [
ForgotPasswordAction((context, email) {
Navigator.pushNamed(
context,
'/forgot-password',
arguments: {'email': email},
);
}),
// Rest of setup
```
We should see it in the `ForgotPasswordScreen`. Now, it displays correctly:
If we don't, it will still work as previously taking the value from the email input from sign-in screen.
This will ensure a smooth and …
> fix(auth): `ForgotPasswordScreen` display email within input box

- packages/firebase_ui_localizations/lib/l10n/firebase_ui_fi.arb
- packages/firebase_ui_localizations/lib/src/all_localizations.dart
- packages/firebase_ui_localizations/lib/src/get_localization.dart
- packages/firebase_ui_localizations/lib/src/lang/fi.dart
This PR adds new language Finnish. The translations are checked but not reviewed by third party.
The melos run analyze noticed error on the original main and these continued to be the same when I did with my changes,
- [ x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x] I updated/added relevant documentation (doc comments with `///`).
- [ x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ x] All unit tests pass (`melos run test:unit:all` doesn't fail).
- [ x] I read and followed …
> feat(firebase_ui_localizations): Add Finnish language localization labels

- packages/firebase_ui_localizations/lib/l10n/firebase_ui_de.arb
- packages/firebase_ui_localizations/lib/src/lang/de.dart
Corrected German Translations for Email Verification (which were previously not translated and just in english).
[CLA]: …
> feat(firebase_ui_localizations): Further German translations for auth labels that were still in English

- packages/firebase_ui_auth/lib/src/widgets/phone_input.dart
When using the PhoneInput widget as described in the "Using widget" or "Building a custom widget" sections [here](https://github.com/firebase/FirebaseUI-Flutter/blob/main/docs/firebase-ui-auth/providers/phone.md), it usually means there are additional fields or other widgets on screen, and therefore the `autofocus: true` which is currently hard-coded into the PhoneInput widget might conflict with the desired UX of that screen.
Note: I see errors in `firebase_ui_firestore` (which also exist in the `main` branch), but no issues in the package which this PR …
> feat(firebase_ui_auth): add autofocus property to PhoneInput widget

- packages/firebase_ui_auth/lib/src/widgets/delete_account_button.dart
previously the wrong navigator was popped when cancelling or confirming the dialog. this resulted in the dialog still beeing visible and the navigator behind it beeing popped. the fix adds the context object to the function parameter, so the right navigator gets popped.
fixes https://github.com/firebase/FirebaseUI-Flutter/issues/212 …
> fix(ui_auth): fix confirmation dialog for delete account button

- packages/firebase_ui_localizations/lib/src/get_localization.dart
Locale('nb') wasn't working, so I had a look and noticed a missing string in the "kSupportedLanguages" list.
Forked, updated the package with the string, ran a dependency override to test and the error dissapeared 👍. 
N/A
- [ x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ x ] All unit tests pass (`melos run test:unit:all` doesn't fail).
- [ x ] I read and followed the [Flutter Style Guide].
- [ x ] I signed the [CLA].
- [ x ] …
> fix(ui_localizations): Add missing 'nb' language code to kSupportedLanguages

- melos.yaml
- packages/firebase_ui_auth/example/pubspec.yaml
- packages/firebase_ui_auth/pubspec.yaml
- packages/firebase_ui_database/example/pubspec.yaml
- packages/firebase_ui_database/lib/src/table_builder.dart
- packages/firebase_ui_database/pubspec.yaml
- packages/firebase_ui_firestore/example/pubspec.yaml
- packages/firebase_ui_firestore/lib/src/table_builder.dart
- packages/firebase_ui_firestore/pubspec.yaml
- packages/firebase_ui_localizations/example/pubspec.yaml
- packages/firebase_ui_oauth/example/pubspec.yaml
- packages/firebase_ui_oauth/pubspec.yaml
- packages/firebase_ui_oauth_apple/pubspec.yaml
- packages/firebase_ui_oauth_facebook/pubspec.yaml
- packages/firebase_ui_oauth_google/pubspec.yaml
- packages/firebase_ui_oauth_twitter/pubspec.yaml
- packages/firebase_ui_storage/example/pubspec.yaml
- packages/firebase_ui_storage/pubspec.yaml
- scripts/update_dependencies.dart
- tests/ios/Podfile
- tests/macos/Podfile
- tests/pubspec.yaml
- Tested macOS, iOS and android e2e tests locally. CI is flakey for now and I'll be looking to find a way to test without being blocked by CI. 
- Built all examples in web to prove they build successfully. …
> chore: bump FlutterFire dependencies to latest & update deprecated members to latest

- packages/firebase_ui_auth/lib/src/screens/profile_screen.dart
Instead of using a hardcoded color value, the Theme colors should be used. This is how the component looks right now with dark mode:
As you can see it is not really readable. 
- [x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs. …
> fix(auth): using theme color instead of hardcoded value

- packages/firebase_ui_localizations/lib/l10n/firebase_ui_pt.arb
Some of the strings were not translated to 'pt' and were still in English. 
I also changed:
1. 'e-mail' to 'email', to be consistent with english
2. 'Uso um dos métodos' to 'Use um dos métodos' (typo)
3. 'Informar o código SMS' to 'Introduza o código SMS' (typo)
4. 'Enviamos um link' to 'Enviámos um link' (typo)
> fix(ui localizations): fixed typos and added translations to 'pt' (Portugese)

- packages/firebase_ui_auth/lib/src/screens/profile_screen.dart
See https://github.com/firebase/FirebaseUI-Flutter/pull/346
"Previously the wrong navigator was popped when cancelling or confirming the dialog. this resulted in the dialog still beeing visible and the navigator behind it beeing popped. the fix adds the context object to the function parameter, so the right navigator gets popped.".
This same logic needs to be applied to the showUnlinkConfirmationDialog dialog so it obtains the correct context and pops correctly.
fixes https://github.com/firebase/FirebaseUI-Flutter/issues/212
Does your PR require plugin users …
> fix(ui_auth): fix confirmation dialog for unlink account button in profile screen

- packages/firebase_ui_auth/README.md
Demonstrate that the `UserCreated` event must be handled
Fixes https://github.com/firebase/FirebaseUI-Flutter/issues/382
[CLA]: …
> docs(firebase_ui_auth): Handle `UserCreated` event in `README` example

- packages/firebase_ui_auth/lib/src/screens/profile_screen.dart
Fix confirmed here: https://github.com/firebase/FirebaseUI-Flutter/issues/353#issuecomment-2471823335
fixes https://github.com/firebase/FirebaseUI-Flutter/issues/353 …
> fix(auth): remove listener on dispose and only call setState when mounted

- packages/firebase_ui_auth/lib/src/oauth/provider_resolvers.dart
- packages/firebase_ui_auth/lib/src/screens/profile_screen.dart
- packages/firebase_ui_oauth/lib/src/oauth_provider_button_style.dart
In the `ProfileScreen`, use the OAuth provider icon as a fallback if available
Replaces #451 
closes https://github.com/firebase/FirebaseUI-Flutter/issues/383
[pub versioning philosophy]: …
> feat(firebase_ui_auth): Use icon from OAuth provider as a fallback in ProfileScreen

- packages/firebase_ui_storage/lib/src/widgets/progress_indicator.dart
Checks if progress is NaN and if true, sets it to 0
fixes #490 
> fix(ui_storage): progress is NaN when both bytesTransferred & totalBytes are 0

- packages/firebase_ui_localizations/lib/l10n/firebase_ui_fr.arb
- packages/firebase_ui_localizations/lib/l10n/firebase_ui_pt.arb
- packages/firebase_ui_localizations/lib/src/default_localizations.dart
- packages/firebase_ui_localizations/lib/src/lang/ar.dart
- packages/firebase_ui_localizations/lib/src/lang/de.dart
- packages/firebase_ui_localizations/lib/src/lang/en.dart
- packages/firebase_ui_localizations/lib/src/lang/es.dart
- packages/firebase_ui_localizations/lib/src/lang/es_419.dart
- packages/firebase_ui_localizations/lib/src/lang/fi.dart
- packages/firebase_ui_localizations/lib/src/lang/fr.dart
- packages/firebase_ui_localizations/lib/src/lang/he.dart
- packages/firebase_ui_localizations/lib/src/lang/hi.dart
- packages/firebase_ui_localizations/lib/src/lang/hu.dart
- packages/firebase_ui_localizations/lib/src/lang/id.dart
- packages/firebase_ui_localizations/lib/src/lang/it.dart
- packages/firebase_ui_localizations/lib/src/lang/ja.dart
- packages/firebase_ui_localizations/lib/src/lang/ko.dart
- packages/firebase_ui_localizations/lib/src/lang/nb.dart
- packages/firebase_ui_localizations/lib/src/lang/nl.dart
- packages/firebase_ui_localizations/lib/src/lang/pl.dart
- packages/firebase_ui_localizations/lib/src/lang/pt.dart
- packages/firebase_ui_localizations/lib/src/lang/ro.dart
- packages/firebase_ui_localizations/lib/src/lang/ru.dart
- packages/firebase_ui_localizations/lib/src/lang/th.dart
- packages/firebase_ui_localizations/lib/src/lang/tr.dart
- packages/firebase_ui_localizations/lib/src/lang/uk.dart
- packages/firebase_ui_localizations/lib/src/lang/zh.dart
- packages/firebase_ui_localizations/lib/src/lang/zh_tw.dart
Many french translation values were missing.
Many files are edited because I run `dart run firebase_ui_localizations:gen_l10n`. 
`firebase_ui_fr.arb` is now well translated.
`firebase_ui_pt.arb` is now fixed.
closes https://github.com/firebase/FirebaseUI-Flutter/issues/508 …
> feat: Add missing translation values for French and update some Portugese

- packages/firebase_ui_localizations/lib/src/l10n.dart
Make the static const
The const keyword must be moved to let the static be const.
I want to use the static as a const.
[CLA]: …
> fix(firebase_ui_localizations): Expose const explicitly
